# Site wide configuration

title: Research Website of Monah Abou Alezz
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Monah Abou Alezz, PhD
  avatar: pic_monah_abou_alezz.jpg
  bio: "Postdoctoral researcher | Senior bioinformatician | Trainer. <br />
  
  <br />
  
  Welcome to my research world. Highlighting my academic and research journey. "
  email: aboualezz.monah@hsr.it
  # Do not include the @ symbol in your Twitter username
  twitter: MonahAbouAlezz
  linkedin: monah-abou-alezz-phd-06a948ba
  github: monahton
  orcid: 0000-0002-2006-4250
  researchgate: Monah_Abou_Alezz
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: 882eaNUAAAAJ
  facebook: monah.ezz
  instagram: monahton
  bing-verify:
  stackoverflow: 9516021/monahaboualezz
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
google_analytics: G-3D9W0NDLPT
